### ISSUE TITLE
Hard crash when putting Mekanism basic tank in Thermal's Tinkers' Workbench

### ISSUE THREAD

**Issue by zlepper** [KingLemming/1.16#15]
Crash log: https://paste.feed-the-beast.com/view/b40d494c

How to reproduce:
Put a watering can in the changing slot of the Tinkers' Workbench and a full Mekanisk Basic tank into the "fluid" slot. Game crashes with above exceptions. I cannot open the world afterwards. (Managed to recover the world by using some external world edit program to delete the block). 

Originally reported to the Direwolf20 modpack here: https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/58

**Comment by KingLemming** [comment]
Fixed in version 1.1.6.
