### ISSUE TITLE
[Ensorcellation] Soulbound only applicable to breakable/vanishable items

### ISSUE THREAD

**Issue by ChloeDawn** [KingLemming/1.16#19]
**Mod version:** 1.16.3-1.1.2
**Forge version:** 36.0.22

Items such as clocks, filled maps, Thermal Innovation's tools, [Botania](https://www.curseforge.com/minecraft/mc-mods/botania)'s curios, and [Create](https://www.curseforge.com/minecraft/mc-mods/create)'s wrench cannot be soulbound due to this restriction. It is a side-effect of making it use `EnchantmentType.VANISHABLE`. *I'm unsure if this is intended behavior or not so decided to report it.*

NOTE: This restriction is not present when using an anvil in creative mode

**Comment by KingLemming** [comment]
It was sort of intended at the time, but I've come up with a good solution for 1.2. :)
