### ISSUE TITLE
Buggy machine container behavior

### ISSUE THREAD

**Issue by whizvox** [KingLemming/1.16#21]
Minecraft: 1.16.5
Thermal Expansion: 1.16.3-1.1.6
Forge: 36.0.43

I've been playing with the phytogenic insolator, and noticed two bits of weird behavior. I tested this on other machines, and it seems to happen across all machines whenever applicable.

1. Machines can create stacks with over 64 items in them. It doesn't appear to be splitting the stacks when going over the limit of 64.

![2021-02-25_18 38 09](https://user-images.githubusercontent.com/8813286/109249971-96e39480-779d-11eb-828a-4dfacb23d6a6.png)

2. It an item exists in an output slot and its stack size is less than 64, you can shift click matching items from your inventory into that same output slot.

**Comment by KingLemming** [comment]
Intended. Please read the manual.
