### ISSUE TITLE
Incorrect Recipe Name

### ISSUE THREAD

**Issue by Jerome226** [KingLemming/1.16#27]
I noticed the Induction Smelter recipe for Pig Iron have a typo.

"thermal:compat/tconstruct/smelter_alloy_tconstruct_pigiron_ingot" should be "thermal:compat/tconstruct/smelter_alloy_tconstruct_pig_iron_ingot" because the ingot name is "pig_iron" and not "pigiron".

**Comment by ShinyPorygon** [comment]
Already fixed
