### ISSUE TITLE
Redstone Flux Cells don't seem to use RF Transfer modifier from augments

### ISSUE THREAD

**Issue by TheRealWormbo** [KingLemming/1.16#30]
When putting a High-Flux RF Coil or Stabilized RF Coil into a Redstone Flux Cell, the configurable maximum transfer rate of the Flux Cell scales with the augment's RF Capacity modifier, not its RF Transfer modifier.

Steps to reproduce:
1. Place an unenchanted and unaugmented Redstone Flux Cell. Its capacity is 1M RF and it can be configured to provide or receive up to 1000 RF/t.
2. Put a High-Flux RF Coil (RF Capacity x2, RF Transfer x6) into one of the Redstone Flux Cell's augment slots.
3. Open the Redstone Flux Cell's UI and increase either of the transfer rates to the maximum possible value.

Observed result:
* The Redstone Flux Cell has a capacity of 2M RF and transfer rates can be increased up to 2000 RF/t.

Expected result:
* The Redstone Flux Cell has a capacity of 2M RF and transfer rates can be increased up to 6000 RF/t.

**Comment by ShinyPorygon** [comment]
After some testing it looks like the Stabilized RF Coil has both multiplied by 6. So perhaps it was a mistype between the two.

**Comment by TheRealWormbo** [comment]
I dug into the code, because I was curious. It looks like `ThermalBaseTile::finalizeAttributes` uses `TAG_AUGMENT_RF_STORAGE` to determine both `energyStorageMod` and `energyXferMod`. A copy&paste error, I assume, since the latter should probably use `TAG_AUGMENT_RF_XFER` instead. Also, `energyXferMod` seems to be affected by Holding there, which may or may not be intentional, I can't tell.

**Comment by KingLemming** [comment]
Yeah, copy/paste as I was reorganizing code. Fixed in dev.
