### ISSUE TITLE
Missing recipe for Flux Efficiency augment and more

### ISSUE THREAD

**Issue by ChromaPIE** [KingLemming/1.16#31]
Moreover, the localization for the key `info.thermal.augment.attr.MachineSpeed` used to indicate the speed of the machine is `Maximum Power`. It's a bit confusing to me and I'm not sure if it makes sense.

**Comment by ShinyPorygon** [comment]
Your question regarding the `info.thermal.augment.attr.MachineSpeed` I can answer. It still increases maximum power by 100% per augment but it now also lowers the efficiency of the machine by 1.1x. In other words it increases the maximum power but it also increases how much energy is required for an operation. If that makes sense
