### ISSUE TITLE
Induction Smelter pulls incompatible ingredients via auto-input and lacks automated content inspection options

### ISSUE THREAD

**Issue by TheRealWormbo** [KingLemming/1.16#32]
The problem: When trying to process a mixed input, e.g. various ores, the induction smelter's auto-input will pull in up to three different ore types it supports, but at the same time, which obviously does not match any recipe. Additionally it's impossible to detect the content of an induction smelter using most automation options form various mods, such as a vanilla comparator or something like Create's "Content Observer" block that can be configured to provide a signal when a certain item is present. This prevents auto-crafting setups with multiple different recipes from working properly, since there is no way easy way to detect whether the previous inputs were already processed. The various access configurations for the Induction Smelter's sides have no effect in this regard.

While auto-input already is smart enough to only pull in items that are used in any recipes, it should probably also make sure the items already in the machine are part of the same recipe. Additionally, to allow other mods to properly insert ingredients for an expected recipe only when no other items are present (e.g. an AE2 ME Interface in blocking mode), they need to be able to see the content of the recipe input slots, even if they should not be able to take anything out form there. It'd probably be okay (or even good) if the catalyst slot stays invisible in that regard.

**Comment by ShinyPorygon** [comment]
The auto grab everything is intentional behavior for the induction smelter

**Comment by TheRealWormbo** [comment]
Okay, not great and not very useful, but so be it.

What about the "external automation can't see the contents" issue, though?

**Comment by KingLemming** [comment]
You need to take that up with them. There's no reason they'd be unable to see the contents.

**Comment by TheRealWormbo** [comment]
Just wondering: What, in your opinion, would be the proper way for another mod to detect that specifically some (not all) input slots of a Thermal machine are non-empty?
