### ISSUE TITLE
[Ensorcellation] Issue with enchanting horse armor

### ISSUE THREAD

**Issue by ZephaniahNoah** [KingLemming/1.16#34]
Ensorcellation allows horse armor to be enchanted in the enchanting table. But other modded horse armors can not be enchanted due to there just being a [hard coded override for each vanilla horse armor](https://github.com/KingLemming/1.16/blob/02b33e17bb1d09e9a879ceddb5b6fc433b594351/CoFHCore/src/main/java/cofh/core/init/CoreItems.java).
There are a couple of ways I can think supporting modded horse armors.
1. Mixin/coremod.
2. Looping through all items and overriding any `HorseArmorItem`.

Either way, the enchantability could be based on the horse armor protection value. I know that means it wouldn't match the vanilla values. But you could also just hard code the vanilla armor overrides and dynamically override modded ones.
I tried coming up with a solution but there were too many errors in the project I set up.

**Comment by KingLemming** [comment]
Sorry, I balance around vanilla and that's really all that can be requested. Mixins have a tendency to conflict in some nasty ways.
