### ISSUE TITLE
No Readme

### ISSUE THREAD

**Issue by AverageComet250** [KingLemming/1.16#35]
Please add a Readme file

**Comment by KingLemming** [comment]
Okay, but you're not gonna like it.

**Comment by AverageComet250** [comment]
There still isn't a readme

**Comment by ShinyPorygon** [comment]
Patience is a virtue. It's all rights reserved if that's what you want to know.

**Comment by AverageComet250** [comment]
All rights reserved is the license since no license file is given, the Readme says what the project actually is

**Comment by KingLemming** [comment]
Crazy thought, it's not actually any concern of yours.
