### ISSUE TITLE
[Thermal Expansion] Woot compat recipes eat casting dies

### ISSUE THREAD

**Issue by linuxdaemon** [KingLemming/1.16#36]
When using the Woot compat recipes in the Press, the die is used up. This is inconsistent with the behavior natively in Woot. Recipe is defined here https://github.com/KingLemming/1.16/blob/de2357cdaddade214b5daf12712ca58e185a6f09/ThermalExpansion/src/main/resources/data/thermal/recipes/compat/woot/press_woot_black_dye_casing.json#L1-L23

The issue seems to be https://github.com/KingLemming/1.16/blob/de2357cdaddade214b5daf12712ca58e185a6f09/ThermalExpansion/src/main/java/cofh/thermal/expansion/tileentity/machine/MachinePressTile.java#L74-L76 as the Woot dies are not registered as `MACHINE_DIES`.

## Versions
Forge 36.1.24
CoFH Core 1.2.1
Thermal Expansion 1.2.0
Woot 1.16.5-1.0.7.0
Modpack: AllTheMods 6 1.6.7

**Comment by ShinyPorygon** [comment]
Woot compat is being removed, you actually reminded me to do it. We have no good way to get around this so we decided in removing it a few weeks ago. We don't want to tag other mods items just because of compatibility, and this bypassed part of the mods systems.
