### ISSUE TITLE
[Ensorcellation] Curios trinkets not staying in slot with Soulbound enchant on death.

### ISSUE THREAD

**Issue by Sarelth** [KingLemming/1.16#41]
Specifically, the trinkets from the ARtifacts mod are not staying in the curios slots, though I have not tested with other trinkets in the modpack I am playing which is "Enigmatica 6". Minecraft version is 1.16.5.

**Comment by KingLemming** [comment]
Yeah, I don't support Curios. Not exactly a bug. Do they stay in inventory?

**Comment by Sarelth** [comment]
They do get sent back to the inventory.

**Comment by KingLemming** [comment]
That's good enough then IMO. I don't think I can do better without explicit dependency on Curios.
