### ISSUE TITLE
middle clicking blocks (getPickBlock) on Thermal machines preserves some NBT

### ISSUE THREAD

**Issue by jaredlll08** [KingLemming/1.16#6]
So I don't know if this is intended or not, but when you middle click a block, like the dynamo, it preserves some of it's NBT, namely the output energy bar and the augments.

It doesn't preserve the items in the item slot though, for example, I middle clicked this dynamo

![image](https://user-images.githubusercontent.com/5553605/99740926-9ff70280-2ad8-11eb-8e70-83d29d41c243.png)
When placed down, it turns into 
![image](https://user-images.githubusercontent.com/5553605/99740940-a84f3d80-2ad8-11eb-828d-0f460b1e3cb2.png)

This could be intended, but I figured I would make an issue just in case, since ctrl + middle click does create a NBT copy of blocks (vanilla feature), which does contain the items that were being used

**Comment by KingLemming** [comment]
Intended. There's a config option.
